title = "Amazon EKS 사용하기"
googleAnalytics = ""
anguageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
baseURL = "https://master.d3s71i2n51x60t.amplifyapp.com/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Jooyoung Kim"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> EKS Workshop"
  url = "https://www.eksworkshop.com/"
  weight = 1000

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Container Roadmap "
  url = "https://github.com/aws/containers-roadmap/projects/1"
  weight = 1010

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github for workshop code"
  url = "https://github.com/joozero/amazon_eks"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-info'></i> Feedback"
  url = "https://github.com/joozero/amazon_eks"
  weight = 1030

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = ""
