CanonifyURLs=true
languageCode = "ko-KR"
defaultContentLanguage = "ko"
googleAnalytics = ""

title = "Amazon EKS로 웹 페이지 구성하기"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
relativeURLs=true
baseURL = "https://master.d3s71i2n51x60t.amplifyapp.com/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  description = "Build Web Application with Amazon EKS"
  author = "Jooyoung Kim"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> EKS Workshop"
  url = "https://www.eksworkshop.com/"
  weight = 1000

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Container Roadmap "
  url = "https://github.com/aws/containers-roadmap/projects/1"
  weight = 1010

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github for workshop code"
  url = "https://github.com/joozero/amazon-eks-flask"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fas fa-heart'></i> Feedback"
  url = "https://github.com/joozero/amazon_eks"
  weight = 1030

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = ""
