title = "Amazon Forecast 사용하기"
googleAnalytics = "UA-174210693-1"
anguageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
baseURL = "https://master.d3s71i2n51x60t.amplifyapp.com/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "forecast-demogo-members(Junghee Kang, Jooyoung Kim, Dongmin Lee)"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-facebook-square'></i> Facebook"
  url = "https://www.facebook.com/groups/awskrug/"
  weight = 1030

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/studydev/hugo-workshop"
  weight = 1040

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://forecast-demogo-web-site?region=ap-northeast-2"
